apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  type: NodePort  # Exposes the service on a static port on each node in the cluster
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80        # The port the service will listen on
      targetPort: 8080 # The port the container is exposing inside the pod
      nodePort: 30080  # The port that will be exposed on each node (in this case, 30080)