---
- name: Install Maven and Docker on Ubuntu & CentOS
  hosts: all
  become: yes
  vars:
    ansible_user: msh

  tasks:
    - name: Detect OS Family
      set_fact:
        is_ubuntu: "{{ ansible_os_family == 'Debian' }}"
        is_centos: "{{ ansible_os_family == 'RedHat' }}"

    - name: Update package index (Ubuntu)
      apt:
        update_cache: yes
      when: is_ubuntu

    - name: Update package index (CentOS)
      yum:
        name: '*'
        state: latest
      when: is_centos

    - name: Install Maven (Ubuntu)
      apt:
        name: maven
        state: present
      when: is_ubuntu

    - name: Install Maven (CentOS)
      yum:
        name: maven
        state: present
      when: is_centos
    - name: Install required packages for Docker (Ubuntu)
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
      when: is_ubuntu

    - name: Install required packages for Docker (CentOS)
      yum:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
        state: present
      when: is_centos

    - name: Add Docker repo (Ubuntu)
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present
      when: is_ubuntu

    - name: Add Docker repo (CentOS)
      command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
      args:
        creates: /etc/yum.repos.d/docker-ce.repo
      when: is_centos
    - name: Install Docker (Ubuntu)
      apt:
        name: docker-ce
        state: present
        update_cache: yes
      when: is_ubuntu

    - name: Install Docker (CentOS)
      yum:
        name: docker-ce
        state: present
      when: is_centos

    - name: Ensure Docker service is running
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Add current user to Docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
